plugins {
    id 'java'
    id 'checkstyle'
}

group = 'com.flexksx'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

checkstyle {
    toolVersion = '14.1.0'
    configFile = file('../checkstyle.xml')
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.tngtech.archunit:archunit:1.5.0'
    testImplementation 'com.puppycrawl.tools:checkstyle:14.1.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}